#!/usr/bin/env node
import { existsSync, mkdirSync, rmSync, writeFileSync, cpSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const mobileRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(mobileRoot, "..");
const wwwRoot = join(mobileRoot, "www");

const ROOT_FILES = [
  "index.html",
  "manifest.webmanifest",
  "css/styles.css",
  "fonts/fonts.css",
  "fonts/OFL-Outfit.txt",
  "fonts/files/QGYvz_MVcBeNP4NJuktqQ4E.woff2",
  "fonts/files/QGYvz_MVcBeNP4NJtEtq.woff2",
  "js/learning.js",
  "js/store.js",
  "js/srs.js",
  "js/voice.js",
  "js/exam_integrity.js",
  "js/data-loader.js",
  "js/app.js",
  "js/experience-contract.js",
  "data/words.js",
  "data/grammar.js",
  "data/sentences.js",
  "data/idioms.js",
  "data/comprehension.js",
  "icons/favicon-32.png",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png"
];

const FORBIDDEN = /hanapath|hangul|jamo|korean|audio_map|korean_5000|korean_supplementary/i;

function fail(message) {
  console.error(`prepare-web: ERROR ${message}`);
  process.exit(1);
}

const indexHtml = readFileSync(join(repoRoot, "index.html"), "utf8");
if (FORBIDDEN.test(indexHtml)) fail("index.html still references Korean/HanaPath runtime assets");
if (indexHtml.includes("sw.js")) {
  // Native payload must not register a service worker; the browser index may.
}

if (existsSync(wwwRoot)) {
  if (!existsSync(join(wwwRoot, ".nederpath-generated")) && readdirSync(wwwRoot).length > 0) {
    fail(`refusing to delete ${wwwRoot}: missing .nederpath-generated marker`);
  }
  rmSync(wwwRoot, { recursive: true, force: true });
}
mkdirSync(wwwRoot, { recursive: true });
writeFileSync(join(wwwRoot, ".nederpath-generated"), "Generated by mobile/scripts/prepare-web.mjs. Safe to delete.\n");

for (const file of ROOT_FILES) {
  const src = join(repoRoot, file);
  if (!existsSync(src)) fail(`missing required payload file ${file}`);
  const dest = join(wwwRoot, file);
  mkdirSync(dirname(dest), { recursive: true });
  cpSync(src, dest);
}

const nativeIndex = indexHtml
  .replace(/\s*<script src="\.\/js\/sw-register\.js"><\/script>/, "");
writeFileSync(join(wwwRoot, "index.html"), nativeIndex, "utf8");

const packed = ROOT_FILES.join("\n");
if (FORBIDDEN.test(packed)) fail("payload allowlist contains Korean assets");

console.log(`prepare-web: wrote ${ROOT_FILES.length} files to mobile/www (service worker excluded)`);
