// NederPath Sentence Bank Generator
// Generates curated Dutch benchmark & practice sentences with stable IDs,
// CEFR levels (A1-C1), grammatical tags, and validated surface targetWords.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { validateRegistry, createIdAllocator } from "./id_allocator.mjs";
import { normalizeSentenceKey, validateSentenceRow } from "./sentence_norm.mjs";
import { AUTHORED_SENTENCES } from "./authored_sentences.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SENTENCE_REGISTRY_PATH = join(ROOT, "data", "sentence_ids.json");
const SENTENCES_OUTPUT_PATH = join(ROOT, "data", "sentences.js");

// Historical 13 base sentences that existed in the original 5,050-item template corpus
const HISTORICAL_BASE_ENTRIES = {
  [normalizeSentenceKey("Ik woon al drie jaar met veel plezier in Utrecht.")]: "snt-00001",
  [normalizeSentenceKey("Morgenochtend om negen uur neem ik de trein naar Amsterdam Centraal.")]: "snt-00002",
  [normalizeSentenceKey("De bakker om de hoek verkoopt elke dag vers volkorenbrood.")]: "snt-00003",
  [normalizeSentenceKey("Zij heeft gisteren een prachtige nieuwe fiets gekocht.")]: "snt-00004",
  [normalizeSentenceKey("Omdat het vanochtend hard regende, ben ik met de bus naar kantoor gegaan.")]: "snt-00005",
  [normalizeSentenceKey("Jan staat elke werkdag om kwart over zes op om de files te vermijden.")]: "snt-00006",
  [normalizeSentenceKey("Kun je mij alstublieft even helpen met het tillen van deze zware koffer?")]: "snt-00007",
  [normalizeSentenceKey("In het weekend gaan wij graag wandelen in de duinen bij Bloemendaal.")]: "snt-00008",
  [normalizeSentenceKey("Als je regelmatig oefent, zul je merken dat je Nederlands snel vooruitgaat.")]: "snt-00009",
  [normalizeSentenceKey("Het nieuwe museumgebouw werd vorig jaar feestelijk geopend door de burgemeester.")]: "snt-00010",
  [normalizeSentenceKey("Hoewel het kabinet nieuwe maatregelen heeft aangekondigd, blijft de woningmarkt gespannen.")]: "snt-00011",
  [normalizeSentenceKey("De commissie heeft besloten het voorstel nader te laten onderzoeken door onafhankelijke experts.")]: "snt-00012",
  [normalizeSentenceKey("Mocht de situatie onverhoopt escaleren, dan treedt het nationale noodplan onmiddellijk in werking.")]: "snt-00013"
};

const ALLOCATOR_OPTIONS = {
  prefix: "snt-",
  idPattern: /^snt-(\d+)$/,
  digits: 5,
  normalize: normalizeSentenceKey
};

export function buildSentencesBank() {
  let initialRegistry;
  if (existsSync(SENTENCE_REGISTRY_PATH)) {
    initialRegistry = JSON.parse(readFileSync(SENTENCE_REGISTRY_PATH, "utf8"));
  } else {
    // Initialize with historical entries and highWaterMark: 5050 to never recycle retired template IDs
    initialRegistry = {
      version: 1,
      highWaterMark: 5050,
      entries: { ...HISTORICAL_BASE_ENTRIES }
    };
  }

  const validated = validateRegistry(initialRegistry, ALLOCATOR_OPTIONS);
  const allocator = createIdAllocator(validated, ALLOCATOR_OPTIONS);

  const sentences = [];
  for (let i = 0; i < AUTHORED_SENTENCES.length; i++) {
    const raw = AUTHORED_SENTENCES[i];
    const key = normalizeSentenceKey(raw.nl);
    const id = allocator.assignId(key);
    const targetWord = raw.targetWord || (raw.targetWords && raw.targetWords[0]) || "";
    const targetWords = raw.targetWords || (targetWord ? [targetWord] : []);

    const record = {
      id,
      nl: raw.nl,
      en: raw.en,
      level: raw.level,
      tags: raw.tags,
      category: raw.category,
      targetWord,
      targetWords,
      clozeEligible: true,
      provenance: "curated",
      curated: true
    };

    const errs = validateSentenceRow(record);
    if (errs.length > 0) {
      throw new Error(`Sentence at index ${i} (${record.nl}) failed validation:\n - ${errs.join("\n - ")}`);
    }

    sentences.push(record);
  }

  const updatedRegistry = allocator.toRegistry();
  return { sentences, registry: updatedRegistry };
}

export function writeSentencesBank() {
  const { sentences, registry } = buildSentencesBank();

  // Save deterministic registry
  const sortedEntries = {};
  for (const k of Object.keys(registry.entries).sort((a, b) => a.localeCompare(b, "nl-NL"))) {
    sortedEntries[k] = registry.entries[k];
  }
  const registryOutput = JSON.stringify({
    version: registry.version,
    highWaterMark: registry.highWaterMark,
    entries: sortedEntries
  }, null, 2) + "\n";

  writeFileSync(SENTENCE_REGISTRY_PATH, registryOutput, "utf8");

  // Save JS data file
  const jsContent = `// AUTO-GENERATED by scripts/generate_sentences.mjs - do not edit by hand.
// ${sentences.length} curated Dutch benchmark & practice sentences across CEFR levels A1-C1.
globalThis.NP_SENTENCES = ${JSON.stringify(sentences, null, 2)};
`;

  writeFileSync(SENTENCES_OUTPUT_PATH, jsContent, "utf8");
  console.log(`Generated ${sentences.length} curated sentences (IDs high-water mark: ${registry.highWaterMark})`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeSentencesBank();
}
