// NederPath curated comprehension curriculum generator.
// Only independently authored passages belong here; topic-swapped expansion is prohibited.
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { passages as a1 } from "./comprehension/passages_a1.mjs";
import { passages as a2 } from "./comprehension/passages_a2.mjs";
import { passages as b1 } from "./comprehension/passages_b1.mjs";
import { passages as b2 } from "./comprehension/passages_b2.mjs";
import { passages as c1 } from "./comprehension/passages_c1.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const RAW_PASSAGES = [...a1, ...a2, ...b1, ...b2, ...c1];

const PASSAGE_IDS = new Map([
  ["Een Ochtend in Utrecht", "comp-001"],
  ["Boodschappen Doen op de Zaterdagmarkt", "comp-002"],
  ["De Nederlandse Fietscultuur", "comp-003"],
  ["Een Afspraak bij de Huisarts", "comp-004"]
]);

function rotateQuestionOptions(question, passageIndex, questionIndex) {
  const options = [...question.options];
  const offset = (passageIndex + questionIndex) % options.length;
  return {
    ...question,
    options: options.slice(offset).concat(options.slice(0, offset)),
    correct: (question.correct - offset + options.length) % options.length
  };
}

const compiledPassages = RAW_PASSAGES.map((passage, passageIndex) => ({
  id: passage.id || PASSAGE_IDS.get(passage.title),
  level: passage.level,
  title: passage.title,
  titleEn: passage.titleEn,
  theme: passage.theme,
  readingTimeMin: passage.minutes,
  paragraphs: passage.paragraphs,
  translation: passage.translation,
  keyVocabulary: passage.vocab || passage.keyVocabulary,
  grammarTargets: passage.grammarTargets,
  questions: passage.questions.map((question, questionIndex) =>
    rotateQuestionOptions(question, passageIndex, questionIndex)
  )
}));

const allowedLevels = new Set(["A1", "A2", "B1", "B2", "C1"]);
const ids = new Set();
const levelCounts = { A1: 0, A2: 0, B1: 0, B2: 0, C1: 0 };
for (const passage of compiledPassages) {
  if (!passage.id) throw new Error(`Missing stable ID for comprehension passage: ${passage.title}`);
  if (ids.has(passage.id)) throw new Error(`Duplicate comprehension ID: ${passage.id}`);
  if (!allowedLevels.has(passage.level)) throw new Error(`Invalid CEFR level: ${passage.level}`);
  ids.add(passage.id);
  levelCounts[passage.level]++;
}

if (compiledPassages.length !== 120) {
  throw new Error(`Expected 120 passages, got ${compiledPassages.length}`);
}
for (const level of allowedLevels) {
  if (levelCounts[level] !== 24) {
    throw new Error(`Expected 24 ${level} passages, got ${levelCounts[level]}`);
  }
}

const header = `// AUTO-GENERATED by scripts/generate_comprehension.mjs - do not edit by hand.
// Independently authored Dutch reading passages with translations, vocabulary,
// grammar targets, and passage-specific questions. Not a templated expansion.
globalThis.NP_COMPREHENSION = `;

writeFileSync(
  join(ROOT, "data", "comprehension.js"),
  header + JSON.stringify(compiledPassages, null, 2) + ";\n"
);
console.log(`Generated ${compiledPassages.length} curated comprehension passages.`);
