// NederPath grammar curriculum serializer.
// Serializes independently authored lesson objects. Does not invent lessons
// by interpolating titles into generic shells.
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { lessons as section1 } from "./grammar/section1.mjs";
import { lessons as section2 } from "./grammar/section2.mjs";
import { lessons as section3 } from "./grammar/section3.mjs";
import { lessons as section4 } from "./grammar/section4.mjs";
import { lessons as section5 } from "./grammar/section5.mjs";
import { lessons as section6 } from "./grammar/section6.mjs";
import { lessons as section7 } from "./grammar/section7.mjs";
import { lessons as section8 } from "./grammar/section8.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function createRule(data) {
  return {
    id: data.id,
    section: data.section,
    sectionTitle: data.sectionTitle,
    level: data.level,
    title: data.title,
    titleNl: data.titleNl,
    summary: data.summary,
    rules: data.rules,
    structuralBreakdown: data.structuralBreakdown,
    examples: data.examples,
    commonMistake: data.commonMistake,
    correction: data.correction,
    difficulty: data.level === "A1" || data.level === "A0" ? "beginner" : (data.level === "A2" || data.level === "B1" ? "intermediate" : "advanced"),
    estimatedTimeMin: data.level === "A1" || data.level === "A0" ? 5 : (data.level === "A2" || data.level === "B1" ? 7 : 10),
    tags: data.tags || [data.sectionTitle.toLowerCase().replace(/[^a-z0-9]+/g, "_"), data.level.toLowerCase()],
    prerequisites: data.prerequisites || [],
    relatedRules: data.relatedRules || [],
    exercises: data.exercises
  };
}

const RULES_DATA = [
  ...section1,
  ...section2,
  ...section3,
  ...section4,
  ...section5,
  ...section6,
  ...section7,
  ...section8
];

RULES_DATA.sort((a, b) => parseInt(a.id.replace("g-", ""), 10) - parseInt(b.id.replace("g-", ""), 10));
const finalizedRules = RULES_DATA.map(createRule);

if (finalizedRules.length !== 120) {
  throw new Error(`Expected 120 authored lessons, got ${finalizedRules.length}`);
}
for (let i = 0; i < finalizedRules.length; i++) {
  const expected = `g-${String(i + 1).padStart(3, "0")}`;
  if (finalizedRules[i].id !== expected) {
    throw new Error(`ID drift at ${i}: ${finalizedRules[i].id}`);
  }
}

const header = `// AUTO-GENERATED by scripts/generate_grammar.mjs - do not edit by hand.
// 120 independently authored Dutch grammar lessons across 8 CEFR sections.
// The generator only serializes curated source modules; it does not template titles.
globalThis.NP_GRAMMAR = `;

writeFileSync(join(ROOT, "data", "grammar.js"), header + JSON.stringify(finalizedRules, null, 2) + ";\n");
console.log(`Generated ${finalizedRules.length} authored grammar lessons.`);
